"use client"
// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";
import Navbar from "./_components/navbar/page";
import { store } from "@/lib/store";
import { Provider } from "react-redux";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] })

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >

      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <Provider store={store}>
          <Navbar />
          {children}
          <Toaster />
          </Provider>
        </ThemeProvider>
      </AppRouterCacheProvider>
       
      </body>
    </html>
  );
}
